#!/bin/zsh
RED='\033[0;31m'
BLUE='\033[0;36m'
NC='\033[0m' # No Color
BOLD=$(tput bold)
NORMAL=$(tput sgr0)
TITLE='\e[7m'
TITLE2='\e[1;30;40m'
ITALIC='\e[3m'

print_usage()
{
	echo "${BOLD}Usage:${NORMAL}"
	echo "	./consume [help] [option=value...]"
	echo "consume csv file rows from memphis"
    echo "${BOLD}Arguments:${NORMAL}"
    echo "    ${BOLD}${ITALIC}help${NORMAL} show this menu"
	echo "  ${BOLD}Options:${NORMAL}"
    echo "    ${TITLE}OPTION\tTYPE\t DEFAULT\t DESCRIPTION\t\t\t\t  ${NC}"
	echo "    ${BOLD}${ITALIC}file${NORMAL}\tstr\t * required\t the csv output file path (relative to ~)"
	echo "    ${BOLD}${ITALIC}station${NORMAL}\tstr\t yzStation\t station name to consume the messages from"
	echo "    ${BOLD}${ITALIC}consumer${NORMAL}\tint\t 1\t\t the number of consumer container"
	echo "    ${BOLD}${ITALIC}debug${NORMAL}\tbool\t true\t\t should print debug messages? [true|false]"
    echo "${BOLD}Example:${NORMAL}"
    echo './consume file=~/output.csv station=kkk debug=true consumer=2'
	exit 254
}
if [[ $# == 0 ]]; then
    print_usage
fi
for ARGUMENT in "$@"
do
   if [[ $ARGUMENT == "help" ]]
   KEY=$(echo $ARGUMENT | cut -f1 -d=)

   KEY_LENGTH=${#KEY}
   VALUE="${ARGUMENT:$KEY_LENGTH+1}"

   export "$KEY"="$VALUE"
done

echo $key
if [[ -z $debug ]]; then
    echo "[INFO] no '${BOLD}debug${NORMAL}' argument given. default: debug=true"
    debug="true"
fi
if [[ -z $station ]]; then
    echo "[INFO] no '${BOLD}station${NORMAL}' argument given. default: station=yzStation"
    station="true"
fi
if [[ -z $consumer ]]; then
    echo "[INFO] no '${BOLD}consumer${NORMAL}' argument given. default: consumer=1"
    consumer="1"
fi

docker exec -it memphisconsumer-consumer-$consumer python consumer.py $file $station $debug